# Generated by Django 6.0.3 on 2026-03-22 01:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0003_cohort_deleted_at_course_deleted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
